# Generated by Django 2.1.4 on 2019-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.PositiveIntegerField(help_text="The robots's ID, given automatically by the server.", primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The robots's name given by the user.", max_length=100, null=True)),
                ('ip_address', models.CharField(help_text="The robots's ip address to communicate with it and given by the user.", max_length=100, null=True)),
            ],
        ),
    ]
